api:
  base_url: https://api.example.com
  binance:
    api_key: HbMs2aPHQfPNh097P8SGWl7PpcjyUUk6I4WURcn6SUaTWjJ8SM8jb4tYSZgLFoBX
    options:
      adjust_time_diff: true
      default_type: spot
      recv_window: 60000
    secret: vVQe126DGUw9BNwSG4gkt9E2DTz1YtiGnP3KzmVWH8AFZJ1SAEsPdOexbuwT68ck
    workaround_enabled: true
  enable_rate_limit: true
  headers:
    connection: close
  retry_attempts: 3
  retry_delay: 1.0
  timeout: 60000
  useproxy: auto
backtest:
  costs:
    commission: 0.001
    slippage: 0.001
  engine: ohlcv
  mode: full
  period:
    end: 2023-3-31
    start: '2023-01-01'
  reporting:
    formats:
    - csv
    - json
    - html
    metrics:
    - sharpe_ratio
    - max_drawdown
    - annualized_return
data:
  cache:
    dir: ./cache
    enabled: true
    max_size: 104857600
    retention_days: 30
  database:
    host: localhost
    name: trading
    password: ''
    port: 3306
    table_prefix: market_
    type: mysql
    user: root
  source:
    backup_source: exchange
    live: false
    primary_source: local
    type: local
  storage:
    historical: data/historical/
    orders: data/order_history.csv
    trades: data/trade_records.json
database:
  echo_sql: false
  pool_size: 5
  timeout: 30
  url: sqlite:///database/trading.sqlite
live:
  exchange:
    environment: production
    name: binance
    rate_limits:
      requests: 20
      timeout: 30
  monitoring:
    interval: 60
    metrics:
    - portfolio_value
    - daily_return
    - position_risk
  safeguards:
    cooldown: 60
    emergency_stop:
      enabled: true
      threshold: 0.1
    max_retries: 3
logging:
  async_write: true
  base_path: ./logs
  categories:
    core:
      level: INFO
      modules:
      - core
      - trading_system
      - mode
      - performance
    data:
      level: INFO
      modules:
      - datasource
      - dataframe
      - database
      - download_data
    exchange:
      level: WARNING
      modules:
      - exchange
      - api
      - binance
      - websocket
    strategy:
      level: INFO
      modules:
      - strategy
      - indicators
      - signals
      - backtest
    system:
      level: INFO
      modules:
      - system
      - cli_runner
      - launcher
      - gui_app
      - async_executor
    utils:
      level: INFO
      modules:
      - utils
      - network
      - config_manager
  combined_log: true
  date_format: '%Y-%m-%d %H:%M:%S%z'
  detailed_format: true
  format: '%(asctime)s | %(levelname)-8s | %(module)-15s | [%(filename)s:%(lineno)d]
    | %(message)s'
  handlers:
    console:
      colors: true
      enabled: true
      level: INFO
    file:
      buffer:
        capacity: 1000
        enabled: true
        flush_interval: 5
      compression: gz
      enabled: true
      encoding: utf-8
  level: INFO
  rotation:
    backup_count: 5
    max_file_size: 10485760
    strategy: size
    time_interval: D
  summary:
    enabled: true
    format: json
    level: WARNING
  syslog:
    enabled: false
    facility: local0
    host: localhost
    port: 514
network:
  connection:
    retry_attempts: 3
    retry_delay: 2
    test_url: https://api.binance.com/api/v3/ping
    timeout: 30
  proxy:
    detection:
      check_common_ports: true
      check_env: true
      check_system: true
      test_connection: true
    enabled: auto
notifications:
  email:
    enabled: false
    recipients:
    - your.email@example.com
  telegram:
    bot_token: YOUR_BOT_TOKEN
    chat_id: YOUR_CHAT_ID
    enabled: false
proxies:
  http: 127.0.0.1:7890
  https: 127.0.0.1:7890
risk:
  drawdown:
    max_portfolio: 0.2
    max_single_trade: 0.1
  stop_loss:
    enabled: true
    max_daily: 0.05
    percentage: 0.02
  take_profit:
    enabled: true
    percentage: 0.05
security:
  credentials:
    encryption: aes-256-cbc
  use_env_vars: true
strategy:
  active: dual_ma
  fallback_strategy: neural_network
  parameters:
    fast_period: 50
    slow_period: 200
    threshold: 0.005
  timeframe: 1h
system:
  backtest_mode: ohlcv
  offline_mode: false
  operational_mode: backtest
  performance:
    max_memory: 1073741824
    max_threads: 4
    task_timeout: 300
  timezone: UTC
trading:
  capital:
    initial: 100000.0
    min_order: 0.001
  execution:
    leverage: 1
    slippage: 0.001
  instruments:
  - BTC/USDT
  limits:
    daily_trades: 50
    max_leverage: 10
    min_volume: 0.001
    position: 0.1
validation:
  required:
  - database.url
  - system.performance.max_threads
  - trading.capital.initial
