# config.yaml
# System Configuration File
# Version: 0.8.0

# ========================
# Network Configuration
# ========================
proxies:
  http: "http://127.0.0.1:7890"       # HTTP proxy address
  https: "http://127.0.0.1:7890"      # HTTPS proxy address

# ========================
# API Configuration
# ========================
api:
  binance:
    apiKey: "your apiKey"                     # Exchange API key (fallback)
    secret: "your secret"                     # Exchange API secret (fallback)
    options:
      adjustForTimeDifference: true   # Auto-adjust server time difference
      recvWindow: 60000               # Order processing window (ms)
      defaultType: 'spot'             # Default market type
  timeout: 60000                      # API request timeout (ms)
  enableRateLimit: true               # Enable rate limiting
  headers:
    Connection: "close"               # HTTP connection policy

# ========================
# Security Configuration
# ========================
security:
  use_env_vars: true                  # Prioritize environment variables
  credentials:
    encryption: "aes-256-cbc"         # Credential encryption method

# ========================
# Core System Configuration
# ========================
system:
  operational_mode: "backtest"        # backtest/live/paper
  timezone: "UTC"                     # System timezone
  performance:
    max_threads: 4                    # Maximum parallel threads
    max_memory: 1073741824            # 1GB memory limit
    task_timeout: 300                 # Asynchronous task timeout (seconds)

# ========================
# Data Configuration
# ========================
data:
  source:
    live: false                       # Enable real-time data streaming
    type: "local"                     # local/exchange data source
  storage:
    historical: "db/historical/"      # Historical data directory
    orders: "db/order_history.csv"    # Order records
    trades: "db/trade_records.json"   # Trade records

# ========================
# TODO: Database independent configuration
# ========================
database:
  url: "sqlite:///database/trading.sqlite"  # Default SQLite connection
  pool_size: 5                              # Connection pool size
  timeout: 30                               # Connection timeout (seconds)
  echo_sql: false                           # Whether to output SQL logs (for debugging)

# ========================
# Configuration file validation tag (for ConfigManager)
# ========================
validation:
  required:  # Required field marks
    - "database.url"
    - "system.performance.max_threads"
    - "trading.capital.initial"

# ========================
# Logging Configuration
# ========================
logging:
  # Directory Structure
  base_path: "./logs"                 # Root directory for all log files
  rotation:
    strategy: "size"                  # Rotation type: size/time
    max_file_size: 10                 # Max size (MB) per log file 
    backup_count: 5                   # Number of historical logs to retain
    time_interval: "D"                # Daily rotation (D=day, H=hour)
  level: INFO
  detailed_format: true

  # Output Configuration
  format: "%(asctime)s | %(levelname)-8s | %(module)-15s | %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S%z"  # ISO-8601 format
  
  # Log Destinations
  handlers:
    file:
      enabled: true
      compression: "gz"
      encoding: "utf-8"
      buffer:                         # buffer configuration
        enabled: true
        capacity: 1000                # Max messages in buffer
        flush_interval: 5
    console:
      enabled: true                   # Enable console output
      level: "WARNING"                # Console-specific level

  async_write: true                   # Enable non-blocking log writing

  # Module-specific Configuration
  modules:
    core:
      level: "INFO"                   # System core logs
      path: "system/core.log"
    execution:
      level: "DEBUG"                  # Order execution details
      path: "trading/execution.log"
    strategy:
      level: "INFO"                   # Strategy decisions
      path: "strategies/main.log"
    risk:
      level: "WARNING"                # Risk management alerts
      path: "risk/management.log"
    data:
      level: "DEBUG"                  # Data pipeline operations
      path: "data/pipeline.log"
    api:
      level: "ERROR"                  # API communication
      path: "network/api.log"
    errors:
      level: "CRITICAL"               # Critical system errors
      path: "errors/system_errors.log"
  
  syslog:
    enabled: false                    # Remote syslog integration
    host: "logs.example.com"
    port: 514

# ========================
# Trading Configuration
# ========================
trading:
  capital:
    initial: 100000                   # Starting capital (USD)
    min_order: 0.001                  # Minimum order size
  instruments:
    - "BTC/USDT"                      # Primary trading pair
    - "ETH/USDT"                      # Secondary trading pair
  execution:
    slippage: 0.001                   # Default slippage allowance
    leverage: 1                       # Trading leverage
  limits:
    position: 0.1                     # Max portfolio allocation
    daily_trades: 50                  # Maximum daily trades
    max_leverage: 10                  # Maximum leverage level
    min_volume: 0.001                 # alo transaction

# ========================
# Risk Management
# ========================
risk:
  stop_loss:
    enabled: true
    percentage: 0.02                  # Default stop-loss
    max_daily: 0.05                   # Daily loss limit
  take_profit:
    enabled: true
    percentage: 0.05                  # Default take-profit
  drawdown:
    max_portfolio: 0.2                # Maximum allowed drawdown
    max_single_trade: 0.1             # Per-trade drawdown limit

# ========================
# Strategy Configuration
# ========================
strategy:
  active: "dual_ma"
  parameters:
    fast_period: 50
    slow_period: 200
    threshold: 0.005
  # 新增：多策略支持
  fallback_strategy: "neural_network"  # Alternate strategy

# ========================
# Backtesting Configuration
# ========================
backtest:
  mode: "full"                        # full/single_pass/walk_forward
  period:
    start: "2023-01-01"               # Backtest start date
    end: "2023-12-31"                 # Backtest end date
  costs:
    commission: 0.001                 # Transaction fee percentage
    slippage: 0.001                   # Simulated slippage
  reporting:
    formats: ["csv", "json", "html"]  # Output formats
    metrics:                          # Performance metrics
      - "sharpe_ratio"
      - "max_drawdown"
      - "annualized_return"

# ========================
# Live Trading Configuration
# ========================
live:
  exchange:
    name: "binance"
    environment: "production"         # production/testnet
    rate_limits:
      requests: 20                    # Max calls/second
      timeout: 30                     # Connection timeout (s)
  monitoring:
    interval: 60                      # Performance snapshot interval (s)
    metrics:
      - "portfolio_value"
      - "daily_return"
      - "position_risk"
  safeguards:
    max_retries: 3                    # Error recovery attempts
    cooldown: 60                      # Retry delay (s)
    emergency_stop:                   # Circuit breaker
      enabled: true
      threshold: 0.1                  # 10% daily loss trigger

# ========================
# Notification Configuration
# ========================
notifications:
  email:
    enabled: false
    recipients:
      - "2354889815@qq.com"
  telegram:
    enabled: false
    bot_token: "YOUR_BOT_TOKEN"
    chat_id: "YOUR_CHAT_ID"